version: '3'

services:
    portainer:
      image: portainer/portainer-ce
      restart: always
      container_name: portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      ports:
        - 9000:9000
        - 9443:9443
        - 8000:8000

volumes:
    portainer_data: